--日志测试实例
do_test("执行Log测试",function()
            local oldLevel = Ins.Log._level
            do_test("测试addTag()",function()
                        Ins.Log:setLevel(0)
                        Ins.Log:info("test","addTag() fail")
                        Ins.Log:debug("test","addTag() fail")
                        Ins.Log:warn("test","addTag() fail")
                        Ins.Log:error("test","addTag() fail")
                        Ins.Log:addTag("test")
                        Ins.Log:info("test","addTag() success")
                        Ins.Log:debug("test","addTag() success")
                        Ins.Log:warn("test","addTag() success")
                        Ins.Log:error("test","addTag() success")
                        Ins.Log:delTag("test")
                        Ins.Log:info("test","addTag() fail")
                        Ins.Log:debug("test","addTag() fail")
                        Ins.Log:warn("test","addTag() fail")
                        Ins.Log:error("test","addTag() fail")
            end)
            for i = 1, 5 do
                do_test("测试日志等级 = " .. i,function()
                            Ins.Log:setLevel(i)
                            Ins.Log:addTag("test")
                            Ins.Log:info("test", i > 1 and "info level fail" or "info level success")
                            Ins.Log:debug("test",i > 2 and "debug level fail" or "debug level success")
                            Ins.Log:warn("test",i > 3 and "warn level fail" or "warn level success")
                            Ins.Log:error("test",i > 4 and "error level fail" or "error level success")
                end)
            end
            Ins.Log:setLevel(oldLevel)
end)
